export const light = {
	'--color-bg-a11y': '#ffffff',
	'--color-text-a11y': '#000000',
	'--color-bg': '#e3f7ff',
	'--color-bg-2': '#fef8ff',
	'--color-text': '#151115',
	'--color-primary': '#fd9fff',
	'--color-landingpage-title': '#fcd13f',
	'--color-landingpage-description': '#b8f1fc',
	'--color-tile': '#99e0ff',
	'--color-accent-1': '#77c5e6',
	'--color-accent-2': '#386682c5',
	'--color-accent-3': '#c4e9f8',
	'--color-accent-4': '#97deff',
	'--color-text-button': '#841755',
	'--color-grass-green': '#1aa67e',
	'--color-chat-left': '#99e0ff',
	'--color-chat-right': '#fbc2fc',
	'--color-chat-border-left': '#62bbd6',
	'--color-chat-border-right': '#de9acf',
	'--shadow-header': '#74005c'
};
