<script lang="ts">
  import { onDestroy, onMount } from "svelte";
  import type * as Monaco from "monaco-editor/esm/vs/editor/editor.api";
  import type { ExerciseData } from "./proxy+page";
   
  let { data } : {data: ExerciseData} = $props();
  let userCode : string = $state(data.template);
  let isDraggingHorizontal : boolean = $state(false);
  let isDraggingVertical : boolean = $state(false);

  let isHorizontalResized : boolean = $state(false);
  let isVerticalResized : boolean = $state(false);

  let isHorizontalHovered : boolean = $state(false);
  let isVerticalHovered : boolean = $state(false);
  
  let wasClicked: boolean = $state(false);

  let editor: Monaco.editor.IStandaloneCodeEditor | null = null;
  let monaco: typeof Monaco | null = null;
  let editorContainer: HTMLElement;

  let main_div: HTMLElement;
  let data_div: HTMLElement;
  let code_div: HTMLElement;
  let terminal_div: HTMLElement;
  let monaco_div: HTMLElement;
  let resize_bar_vertical_div : HTMLElement;
  let resize_bar_horizontal_div : HTMLElement;

  let originalWidthLeft : number;
  let originalWidthRight : number;

  let originalHeightTop : number;
  let originalHeightBottom : number;

  let contentPaneClientStartX: number;
  let contentPaneClientStartY: number;
  
  let defaultVerticalScrollBarWidth: number;
  let defaultHorizontalScrollBarHeight: number;

  const getMonacoTheme = () => {
    let current = document.documentElement.getAttribute('data-theme') || 'light';
    switch (current) {
      case 'light':
        return "vs";
      case 'dark':
        return "vs-dark"; 
      default:
        return "vs";
    }
  }
  
  const parseComputedDimensions = (computedDimension: string) : number => {
    return parseInt(computedDimension.replaceAll('px', ''))
  }

  onMount(async () => {
    setupElements();
    calculateMountedSizing();
    setupDynamicElementSizing();
    try {      
      monaco = (await import("./monaco")).default;
      
      if (!editorContainer || !monaco) return;

      editor = monaco.editor.create(editorContainer, {
        value: userCode,
        language: "java",
        theme: getMonacoTheme(),
        minimap: {
          enabled: false
        },
        readOnly: false,
        automaticLayout: true,
      });
    } catch (error) {
      console.error(error);
    } 
  });

  onDestroy(() => {
    try {
      if (editor) {
        editor.dispose();
        editor = null;
      }
      
      if (monaco) {
        monaco.editor.getModels().forEach((model) => {
          model.dispose();
        });
      }
    
    } catch (error) {
      console.error(error);
    }
  });

const setupElements = () : void => {
  const tmp_main_div : HTMLElement | null = document.getElementById("main-div");
  const tmp_data_div : HTMLElement | null = document.getElementById('data-div');
  const tmp_code_div : HTMLElement | null = document.getElementById('code-holder');
  const tmp_monaco_div : HTMLElement | null = document.getElementById('monaco-container');
  const tmp_terminal_div : HTMLElement | null = document.getElementById('terminal-container');
  const tmp_resize_bar_vertical_div : HTMLElement | null = document.getElementById("resize-bar-holder-vertical");
  const tmp_resize_bar_horizontal_div : HTMLElement | null = document.getElementById("resize-bar-holder-horizontal");
  
  if (!tmp_main_div || !tmp_data_div || !tmp_code_div || !tmp_monaco_div || !tmp_terminal_div || !tmp_resize_bar_vertical_div || !tmp_resize_bar_horizontal_div){ throw new Error(":(");} // 🤷

  main_div = tmp_main_div;
  data_div = tmp_data_div;
  code_div = tmp_code_div;
  monaco_div = tmp_monaco_div;
  terminal_div = tmp_terminal_div;
  resize_bar_vertical_div = tmp_resize_bar_vertical_div;
  resize_bar_horizontal_div = tmp_resize_bar_horizontal_div;
}

const calculateMountedSizing = () : void => {
  originalWidthLeft  = parseComputedDimensions(getComputedStyle(data_div).width);
  originalWidthRight = parseComputedDimensions(getComputedStyle(code_div).width);
  originalHeightTop = parseComputedDimensions(getComputedStyle(monaco_div).height);
  originalHeightBottom = parseComputedDimensions(getComputedStyle(terminal_div).height);

  
  const autoGeneratedSuperMain : HTMLElement | null = main_div.parentElement;
  if (!autoGeneratedSuperMain) return;
  const boundingRec : DOMRect | undefined = autoGeneratedSuperMain.getBoundingClientRect();
  if (!boundingRec) return;

  contentPaneClientStartX = boundingRec?.x + parseComputedDimensions(getComputedStyle(autoGeneratedSuperMain).marginLeft) + parseComputedDimensions(getComputedStyle(autoGeneratedSuperMain).paddingLeft) + parseComputedDimensions(getComputedStyle(main_div).paddingLeft) + parseComputedDimensions(getComputedStyle(main_div).marginLeft);
  contentPaneClientStartY = boundingRec?.y + parseComputedDimensions(getComputedStyle(autoGeneratedSuperMain).marginTop) + parseComputedDimensions(getComputedStyle(autoGeneratedSuperMain).paddingTop) + parseComputedDimensions(getComputedStyle(main_div).marginTop) + parseComputedDimensions(getComputedStyle(main_div).paddingTop);

}

const setupDynamicElementSizing = () : void => {
  const actualScrollBarVertical : HTMLElement = resize_bar_vertical_div.childNodes[0] as HTMLElement;
  const actualScrollBarHorizontal : HTMLElement = resize_bar_horizontal_div.childNodes[0] as HTMLElement;

  actualScrollBarVertical.style.width = getComputedStyle(resize_bar_vertical_div).width;
  defaultVerticalScrollBarWidth = parseComputedDimensions(actualScrollBarVertical.style.width);

  actualScrollBarHorizontal.style.height = getComputedStyle(resize_bar_horizontal_div).height;
  defaultHorizontalScrollBarHeight = parseComputedDimensions(actualScrollBarHorizontal.style.height);

  actualScrollBarVertical.style.left = "50%";
  actualScrollBarVertical.style.transform = `translate(-50%)`;

  actualScrollBarHorizontal.style.left = "50%";
  actualScrollBarHorizontal.style.transform = `translate(-50%)`;
}


const handleDownHorizontal = (e: MouseEvent) => {
  e.preventDefault();
  isDraggingHorizontal = true;
  document.addEventListener('mousemove', handleMouseDraggedHorizontal);
  document.addEventListener('mouseup', handleReleaseHorizontal);
  document.body.style.cursor = "col-resize";
  document.body.style.userSelect = "none"; 
}

const handleDownVertical = (e: MouseEvent) => {
  e.preventDefault();
  isDraggingVertical = true;
  document.addEventListener('mousemove', handleMouseDraggedVertical);
  document.addEventListener('mouseup', handleReleaseVertical);
  document.body.style.cursor = "row-resize";
  document.body.style.userSelect = "none"; 
}


const handleMouseDraggedHorizontal = (e: MouseEvent) => {
  if (!isDraggingHorizontal) return;
  const dx = originalWidthLeft + contentPaneClientStartX - e.clientX;
  data_div.style.width = `${originalWidthLeft - dx}px`;
  code_div.style.width = `${originalWidthRight + dx}px`;   
}

const handleMouseDraggedVertical = (e: MouseEvent) => {
  if (!isDraggingVertical) return;
  const dy = originalHeightTop + contentPaneClientStartY - e.clientY;
  monaco_div.style.height = `${originalHeightTop - dy}px`;
  terminal_div.style.height = `${originalHeightBottom + dy}px`;
}

const handleReleaseHorizontal = () => {
  isDraggingHorizontal = false;

  document.removeEventListener('mousemove', handleMouseDraggedHorizontal);
  document.removeEventListener('mouseup', handleReleaseHorizontal);
  document.body.style.cursor = "auto";
  document.body.style.userSelect = "auto";

  wasClicked = true;
}

const handleReleaseVertical = () => {
  isDraggingVertical = false;
  document.removeEventListener('mousemove', handleMouseDraggedVertical);
  document.removeEventListener('mouseup', handleReleaseVertical);
  document.body.style.cursor = "auto";
  document.body.style.userSelect = "auto";

  wasClicked = true;

}

const toggleVerticalWindowResizeBarResized = () => {
  if (isDraggingHorizontal) return;
  const resize_bar_accent : HTMLElement | null = document.getElementById("vertical-resize-bar-accent");
  const resize_bar : HTMLElement | null = document.getElementById("vertical-resize-bar");
  if (!resize_bar || !resize_bar_accent) return;
  const resize_bar_width = parseComputedDimensions(getComputedStyle(resize_bar).width);
  if (!isVerticalResized){
    resize_bar.style.width = `${resize_bar_width * 3}px`
    isVerticalResized = true;
    resize_bar_accent.style.visibility = "visible";

    if(document.documentElement.getAttribute('data-theme') === "dark"){
      resize_bar.style.background = "rgba(255,255,255,0.35)";
    }else{
      resize_bar.style.background = "#FF0000";
    }
  }else {
    isVerticalResized = false;
    resize_bar.style.background = "var(--color-bg)";
    resize_bar.style.width = `${resize_bar_width / 3}px`
    resize_bar_accent.style.visibility = "hidden";

  }
  resize_bar.style.left = "50%";
  resize_bar.style.transform = `translate(-50%)`;  
}

const toggleHorizontalWindowResizeBarResized = () => {
  if (isDraggingVertical) return;
  const resize_bar_accent : HTMLElement | null = document.getElementById("horizontal-resize-bar-accent");
  const resize_bar : HTMLElement | null = document.getElementById("horizontal-resize-bar");
  if (!resize_bar || !resize_bar_accent) return;
  const resize_bar_height = parseComputedDimensions(getComputedStyle(resize_bar).height);
  if (!isHorizontalResized){
    isHorizontalResized = true;
    resize_bar.style.height = `${resize_bar_height * 3}px`
    resize_bar_accent.style.visibility = "visible";
    if(document.documentElement.getAttribute('data-theme') === "dark"){
      resize_bar.style.background = "rgba(255,255,255,0.35)";
    }else{
      resize_bar.style.background = "#FF0000";
    }
  }else{
    isHorizontalResized = false;
    resize_bar.style.height = `${resize_bar_height / 3}px`;
    resize_bar.style.background = "var(--color-bg)";
    resize_bar_accent.style.visibility = "hidden";
  }
  resize_bar.style.top = "50%";
  resize_bar.style.transform = `translate(-50%)`; 
}

</script>

<main id="main-div" class="flex h-[80vh] w-full my-5 bg-[var(--color-bg)]">
  <div id="data-div" class="flex flex-col text-center w-[30%] h-full overflow-hidden">
    <div class="flex justify-center text-l items-center w-full h-[20%]">
        <span class="m-2">
          {data.name}
        </span>
    </div>
    <div class="w-full h-[80%] bg-[var(--color-tile)] rounded-md text-xs overflow-scroll">
        <p class="mx-2 my-4">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut voluptatem delectus quod nesciunt modi vel adipisci eveniet, iste, molestias odio architecto explicabo incidunt facere quibusdam, beatae fuga corrupti sint possimus!
        </p>
        <hr>
        <p class="mx-2 my-4">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut voluptatem delectus quod nesciunt modi vel adipisci eveniet, iste, molestias odio architecto explicabo incidunt facere quibusdam, beatae fuga corrupti sint possimus!
        </p>
        <hr>
        <p class="mx-2 my-4">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut voluptatem delectus quod nesciunt modi vel adipisci eveniet, iste, molestias odio architecto explicabo incidunt facere quibusdam, beatae fuga corrupti sint possimus!
        </p>
        
    </div>
  </div>

  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div 
  id="resize-bar-holder-vertical" 
  class="w-1 h-full relative overflow-visible" 
  class:hover:cursor-col-resize={!isDraggingHorizontal}
  onmouseenter={!isDraggingHorizontal ? ()=>{
    if (isHorizontalResized){
      handleReleaseVertical();
      toggleHorizontalWindowResizeBarResized();      
    }
    toggleVerticalWindowResizeBarResized();
    isVerticalHovered = true;
  } : undefined}

  onmouseleave={!isDraggingVertical ? () => {
    if(!isDraggingHorizontal && wasClicked){
      isVerticalHovered = false;
      wasClicked = false;
      if (isVerticalResized){
        toggleVerticalWindowResizeBarResized();      
      }
    }else{
        toggleVerticalWindowResizeBarResized();
    }
  } : undefined}
  onmousedown={handleDownHorizontal}
  onmouseup={handleReleaseHorizontal}
>
  <div id="vertical-resize-bar" class="h-full absolute flex flex-col justify-center items-center rounded-full">
    <div id="vertical-resize-bar-accent" class="w-1 h-25 bg-[var(--color-accent-1)] rounded-full none invisible"></div>
  </div>
</div>
  <div id="code-holder" class="w-full h-full flex flex-col px-1">
      <div id="monaco-container" class="w-full h-[85%] rounded-t-md overflow-hidden" bind:this={editorContainer}></div>
      <!-- svelte-ignore a11y_no_static_element_interactions -->
        <div 
          id="resize-bar-holder-horizontal" 
          class="h-1 w-full relative overflow-visible"
          class:hover:cursor-row-resize={!isDraggingVertical}
          onmouseenter={!isDraggingVertical ? ()=>{
            if (!isDraggingHorizontal){
              toggleHorizontalWindowResizeBarResized();
              isHorizontalHovered = true;
            }
          } : undefined}
          onmouseleave={!isDraggingHorizontal ? ()=>{
            if(!isDraggingVertical && wasClicked){
              isHorizontalHovered = false;
              wasClicked = false;
              if(isHorizontalResized){
                toggleHorizontalWindowResizeBarResized();
              }
            }else{
              toggleHorizontalWindowResizeBarResized();
            }
          } : undefined}
          onmousedown={handleDownVertical}
          onmouseup={handleReleaseVertical}
        >
          <div id="horizontal-resize-bar" class="w-full absolute flex justify-center items-center rounded-full">
            <div id="horizontal-resize-bar-accent" class="w-25 h-1 bg-[var(--color-accent-1)] rounded-full none invisible">

            </div>
          </div>
        </div>
      <div id="terminal-container" class="w-full h-[15%] bg-[var(--color-tile)] px-3 py-1 rounded-b-md ">
        <span class="font-mono">&#123;username&#125;@&#123;exercise_name&#125;:/home/&#123;username&#125;/terminal$ </span>
      </div>
  </div>
</main>