<script lang="ts">
  import { onDestroy, onMount } from "svelte";
  import type * as Monaco from "monaco-editor/esm/vs/editor/editor.api";
  import type { ExerciseData } from "./proxy+page";
   
  let { data } : {data: ExerciseData} = $props();
  let userCode = $state(data.template);
  let editor: Monaco.editor.IStandaloneCodeEditor | null = null;
  let monaco: typeof Monaco | null = null;
  let editorContainer: HTMLElement;

  let main_div: HTMLElement;
  let data_div: HTMLElement;
  let code_div: HTMLElement;
  let terminal_div: HTMLElement;
  let monaco_div: HTMLElement;
  let resize_bar_vertical_div : HTMLElement;
  let resize_bar_horizontal_div : HTMLElement;

  let originalWidthLeft : number;
  let originalWidthRight : number;

  let originalHeightTop : number;
  let originalHeightBottom : number;

  let contentPaneClientStartX: number;
  let contentPaneClientStartY: number;
  
  let defaultVerticalScrollBarWidth: number;
  let defaultHorizontalScrollBarHeight: number;

  const getMonacoTheme = () => {
    let current = document.documentElement.getAttribute('data-theme') || 'light';
    switch (current) {
      case 'light':
        return "vs";
      case 'dark':
        return "vs-dark"; 
      default:
        return "vs";
    }
  }
  
  const parseComputedDimensions = (computedDimension: string) : number => {
    return parseInt(computedDimension.replaceAll('px', ''))
  }

  onMount(async () => {
    setupElements();
    calculateMountedSizing();
    setupDynamicElementSizing();
    try {      
      monaco = (await import("./monaco")).default;
      
      if (!editorContainer || !monaco) return;

      editor = monaco.editor.create(editorContainer, {
        value: userCode,
        language: "java",
        theme: getMonacoTheme(),
        minimap: {
          enabled: false
        },
        readOnly: false,
        automaticLayout: true,
      });


      //this is just a test. This executes after the editor mounts so we could add a loading icon while it's getting set-up, sure it's about 200ms but still noticeable
    //   let data_div: HTMLElement | null = document.getElementById("data-div");
    //     if (data_div){
    //         data_div.style.background = "#FF0000";
    //     }

    } catch (error) {
      console.error(error);
    } 
  });

  onDestroy(() => {
    try {
      if (editor) {
        editor.dispose();
        editor = null;
      }
      
      if (monaco) {
        monaco.editor.getModels().forEach((model) => {
          model.dispose();
        });
      }
    
    } catch (error) {
      console.error(error);
    }
  });

const setupElements = () : void => {
  const tmp_main_div : HTMLElement | null = document.getElementById("main-div");
  const tmp_data_div : HTMLElement | null = document.getElementById('data-div');
  const tmp_code_div : HTMLElement | null = document.getElementById('code-holder');
  const tmp_monaco_div : HTMLElement | null = document.getElementById('monaco-container');
  const tmp_terminal_div : HTMLElement | null = document.getElementById('terminal-container');
  const tmp_resize_bar_vertical_div : HTMLElement | null = document.getElementById("resize-bar-holder-vertical");
  const tmp_resize_bar_horizontal_div : HTMLElement | null = document.getElementById("resize-bar-holder-horizontal");
  
  if (!tmp_main_div || !tmp_data_div || !tmp_code_div || !tmp_monaco_div || !tmp_terminal_div || !tmp_resize_bar_vertical_div || !tmp_resize_bar_horizontal_div){ throw new Error(":(");} // 🤷

  main_div = tmp_main_div;
  data_div = tmp_data_div;
  code_div = tmp_code_div;
  monaco_div = tmp_monaco_div;
  terminal_div = tmp_terminal_div;
  resize_bar_vertical_div = tmp_resize_bar_vertical_div;
  resize_bar_horizontal_div = tmp_resize_bar_horizontal_div;
}

const calculateMountedSizing = () : void => {
  originalWidthLeft  = parseComputedDimensions(getComputedStyle(data_div).width);
  originalWidthRight = parseComputedDimensions(getComputedStyle(code_div).width);
  originalHeightTop = parseComputedDimensions(getComputedStyle(monaco_div).height);
  originalHeightBottom = parseComputedDimensions(getComputedStyle(terminal_div).height);

  
  const autoGeneratedSuperMain : HTMLElement | null = main_div.parentElement;
  if (!autoGeneratedSuperMain) return;
  const boundingRec : DOMRect | undefined = autoGeneratedSuperMain.getBoundingClientRect();
  if (!boundingRec) return;

  contentPaneClientStartX = boundingRec?.x + parseComputedDimensions(getComputedStyle(autoGeneratedSuperMain).marginLeft) + parseComputedDimensions(getComputedStyle(autoGeneratedSuperMain).paddingLeft) + parseComputedDimensions(getComputedStyle(main_div).paddingLeft) + parseComputedDimensions(getComputedStyle(main_div).marginLeft);
  contentPaneClientStartY = boundingRec?.y + parseComputedDimensions(getComputedStyle(autoGeneratedSuperMain).marginTop) + parseComputedDimensions(getComputedStyle(autoGeneratedSuperMain).paddingTop) + parseComputedDimensions(getComputedStyle(main_div).marginTop) + parseComputedDimensions(getComputedStyle(main_div).paddingTop);

}

const setupDynamicElementSizing = () : void => {
  const actualScrollBarVertical : HTMLElement = resize_bar_vertical_div.childNodes[0] as HTMLElement;
  const actualScrollBarHorizontal : HTMLElement = resize_bar_horizontal_div.childNodes[0] as HTMLElement;

  actualScrollBarVertical.style.width = getComputedStyle(resize_bar_vertical_div).width;
  defaultVerticalScrollBarWidth = parseComputedDimensions(actualScrollBarVertical.style.width);

  actualScrollBarHorizontal.style.height = getComputedStyle(resize_bar_horizontal_div).height;
  defaultHorizontalScrollBarHeight = parseComputedDimensions(actualScrollBarHorizontal.style.height);

  actualScrollBarVertical.style.left = "50%";
  actualScrollBarVertical.style.transform = `translate(-50%)`;

  actualScrollBarHorizontal.style.left = "50%";
  actualScrollBarHorizontal.style.transform = `translate(-50%)`;
  actualScrollBarHorizontal.style.background = "#FFFF00";
}


const handleDownHorizontal = (e: MouseEvent) => {    
    document.addEventListener('mousemove', handleMouseDraggedHorizontal);
    document.addEventListener('mouseup', handleReleaseHorizontal);
}

const handleDownVertical = (e: MouseEvent) => {    
    document.addEventListener('mousemove', handleMouseDraggedVertical);
    document.addEventListener('mouseup', handleReleaseVertical);
}


const handleMouseDraggedHorizontal = (e: MouseEvent) => {
  const dx = originalWidthLeft + contentPaneClientStartX - e.clientX;
  data_div.style.width = `${originalWidthLeft - dx}px`;
  code_div.style.width = `${originalWidthRight + dx}px`;   
}

const handleMouseDraggedVertical = (e: MouseEvent) => {
  const dy = originalHeightTop + contentPaneClientStartY - e.clientY;
  monaco_div.style.height = `${originalHeightTop - dy}px`;
  terminal_div.style.height = `${originalHeightBottom + dy}px`;
}

const handleReleaseHorizontal = (e: MouseEvent) => {
  document.removeEventListener('mousemove', handleMouseDraggedHorizontal);
  document.removeEventListener('mouseup', handleReleaseHorizontal);
}

const handleReleaseVertical = (e: MouseEvent) => {
  document.removeEventListener('mousemove', handleMouseDraggedVertical);
  document.removeEventListener('mouseup', handleReleaseVertical);
}

const toggleVerticalWindowResizeBarResized = () => {
  const resize_bar : HTMLElement | null = document.getElementById("vertical-resize-bar");
  if (!resize_bar) return;
  const resize_bar_width = parseComputedDimensions(getComputedStyle(resize_bar).width);
  if (defaultVerticalScrollBarWidth === resize_bar_width){
    resize_bar.style.width = `${resize_bar_width * 3}px`
    resize_bar.style.background = "#FF0000";
  }else {
    resize_bar.style.background = "#FFFFFF";
    resize_bar.style.width = `${resize_bar_width / 3}px`
  }
  resize_bar.style.left = "50%";
  resize_bar.style.transform = `translate(-50%)`;  
}

const toggleHorizontalWindowResizeBarResized = () => {
  const resize_bar : HTMLElement | null = document.getElementById("horizontal-resize-bar");
  if (!resize_bar) return;
  const resize_bar_height = parseComputedDimensions(getComputedStyle(resize_bar).height);
  if (defaultHorizontalScrollBarHeight === resize_bar_height){
    resize_bar.style.height = `${resize_bar_height * 2}px`
    resize_bar.style.background = "#FF0000";
  }else{
    resize_bar.style.height = `${resize_bar_height / 2}px`
    resize_bar.style.background = "#FFFFFF";
  }
  resize_bar.style.top = "50%";
  resize_bar.style.transform = `translate(-50%)`; 
}

</script>

<main id="main-div" class="flex h-[80vh] w-full my-5 bg-[var(--color-bg)]">
  <div id="data-div" class="flex flex-col text-center w-[30%] h-full overflow-hidden">
    <div class="flex justify-center text-l items-center w-full h-[20%]">
        <span class="m-2">
          {data.name}
        </span>
    </div>
    <div class="w-full h-[80%] bg-[var(--color-tile)] rounded-md text-xs overflow-scroll">
        <p class="mx-2 my-4">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut voluptatem delectus quod nesciunt modi vel adipisci eveniet, iste, molestias odio architecto explicabo incidunt facere quibusdam, beatae fuga corrupti sint possimus!
        </p>
        <hr>
        <p class="mx-2 my-4">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut voluptatem delectus quod nesciunt modi vel adipisci eveniet, iste, molestias odio architecto explicabo incidunt facere quibusdam, beatae fuga corrupti sint possimus!
        </p>
        <hr>
        <p class="mx-2 my-4">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut voluptatem delectus quod nesciunt modi vel adipisci eveniet, iste, molestias odio architecto explicabo incidunt facere quibusdam, beatae fuga corrupti sint possimus!
        </p>
        
    </div>
  </div>

  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div id="resize-bar-holder-vertical" class="w-[5px] h-full relative hover:cursor-col-resize overflow-visible" 
    onmouseenter={toggleVerticalWindowResizeBarResized}
    onmouseleave={toggleVerticalWindowResizeBarResized} 
    onmousedown={handleDownHorizontal} 
    onmouseup={handleReleaseHorizontal}
  >
    <div id="vertical-resize-bar" class="h-full absolute">

    </div>
  </div>
  <div id="code-holder" class="w-full h-full flex flex-col px-1">
      <div id="monaco-container" class="w-full h-[85%] rounded-t-md overflow-hidden" bind:this={editorContainer}></div>
      <!-- svelte-ignore a11y_no_static_element_interactions -->
        <div id="resize-bar-holder-horizontal" class="h-[5px] w-full relative hover:cursor-row-resize overflow-visible"
          onmouseenter={toggleHorizontalWindowResizeBarResized}
          onmouseleave={toggleHorizontalWindowResizeBarResized}
          onmousedown={handleDownVertical}
          onmouseup={handleReleaseVertical}
          >
          <div id="horizontal-resize-bar" class="w-full absolute bg-amber-50"
          
          >
            
          </div>
        </div>
      <div id="terminal-container" class="w-full h-[15%] bg-[var(--color-tile)] px-3 py-1 rounded-b-md ">
        <span class="font-mono">/&#123;hiya&#125;/terminal&gt; </span>
      </div>
  </div>
</main>