<script lang="ts">
  import { onDestroy, onMount } from "svelte";
  import type * as Monaco from "monaco-editor/esm/vs/editor/editor.api";
  import type { ExerciseData } from "../../../../../../Types/ExerciseData";
  import { userPreferences } from "../../../../../../Stores/theme";
  import { parseComputedDimensions, findWrappingIndices, getOptionalDimesionsString, constGetOptionalDimensionsNumber, parseOptionalDimensions } from "../../../../../../Utils/index";
	import HelperDuck from "../../../../../../Components/CodingPageComponents/HelperDuck.svelte";
	import ExerciseInformation from "../../../../../../Components/CodingPageComponents/ExerciseInformation.svelte";

  let { data } : {data: ExerciseData} = $props();

  let userCode: string = $state(data.template);

  let isDraggingHorizontal: boolean = $state(false);
  let isDraggingVertical: boolean = $state(false);

  let isHorizontalResized: boolean = false;
  let isVerticalResized: boolean = false;
  let wasClicked: boolean = false;
  let isDataDivSnappedToLeft = false;

  let theme: string = $state("light");

  let originalWidthLeft: number;
  let originalWidthRight: number;
  
  let originalHeightTop: number;
  let originalHeightBottom: number;
  
  let contentPaneClientStartX: number;
  let contentPaneClientStartY: number;
  
  let editor: Monaco.editor.IStandaloneCodeEditor | null = null;
  let monaco: typeof Monaco | null = null;
  let editorContainer: HTMLElement;
  
  let dataDiv: HTMLElement = $state(document.createElement("div"));
  
  let mainDiv: HTMLElement;
  let codeDiv: HTMLElement;
  let terminalDiv: HTMLElement;
  let monacoDiv: HTMLElement;
  let resizeBarVerticalDiv: HTMLElement;
  let resizeBarHorizontalDiv: HTMLElement;
  let verticalResizeBarAccent: HTMLElement;
  let verticalResizeBar: HTMLElement;
  let horizontalResizeBarAccent: HTMLElement;
  let resizeVerticalButton: HTMLElement; // TODO come up with a better name here
  
  let horizontalResizeBar: HTMLElement;

  const horizontalResizeBarComputedStyle: CSSStyleDeclaration | undefined = $derived.by(() => {
    if (!horizontalResizeBar) return undefined;
    return getComputedStyle(horizontalResizeBar);
  });


  const unsubscribe = userPreferences.subscribe(value => {
    theme = value.theme;
  })

  $effect(() => {
    /* 
    TODO find something more elegant, this reassignment is necessary as is since $effect() triggers when any state referenced in it's body changes.
    For some reason the theme passed to getMonacoTheme() does not count as a referenced state???
     */
    theme = theme;
    monaco?.editor.setTheme(getMonacoTheme(theme));
  });

  const getMonacoTheme = (passedTheme: string) => {
    switch (passedTheme) {
      case 'light':
        return "vs";
      case 'dark':
        return "vs-dark"; 
      default:
        return "vs";
    }
  }

  onMount(async () => {
    calculateMountedSizing();
    setupDynamicElementSizing();
    try {      
      monaco = (await import("../../../../../../Utils/monaco")).default;
      
      if (!editorContainer || !monaco) return;

      editor = monaco.editor.create(editorContainer, {
        value: userCode,
        language: "java",
        theme: getMonacoTheme(theme),
        minimap: {
          enabled: false
        },
        readOnly: false,
        automaticLayout: true,
      });
    } catch (error) {
      console.error(error);
    } 
  });

  onDestroy(() => {
    try {
      if (editor) {
        editor.dispose();
        editor = null;
      }
      
      if (monaco) {
        monaco.editor.getModels().forEach((model) => {
          model.dispose();
        });
      }
    
    } catch (error) {
      console.error(error);
    } finally {
      unsubscribe();
    }
  });

  const calculateMountedSizing = () : void => {
    originalWidthLeft  = parseComputedDimensions(getComputedStyle(dataDiv).width);
    originalWidthRight = parseComputedDimensions(getComputedStyle(codeDiv).width);
    originalHeightTop = parseComputedDimensions(getComputedStyle(monacoDiv).height);
    originalHeightBottom = parseComputedDimensions(getComputedStyle(terminalDiv).height);

    const autoGeneratedSuperMain: HTMLElement | null = mainDiv.parentElement;
    if (!autoGeneratedSuperMain) return;
    const boundingRec: DOMRect = autoGeneratedSuperMain.getBoundingClientRect();

    contentPaneClientStartX = boundingRec.x + parseComputedDimensions(getComputedStyle(autoGeneratedSuperMain).marginLeft) + parseComputedDimensions(getComputedStyle(autoGeneratedSuperMain).paddingLeft) + parseComputedDimensions(getComputedStyle(mainDiv).paddingLeft) + parseComputedDimensions(getComputedStyle(mainDiv).marginLeft);
    contentPaneClientStartY = boundingRec.y + parseComputedDimensions(getComputedStyle(autoGeneratedSuperMain).marginTop) + parseComputedDimensions(getComputedStyle(autoGeneratedSuperMain).paddingTop) + parseComputedDimensions(getComputedStyle(mainDiv).marginTop) + parseComputedDimensions(getComputedStyle(mainDiv).paddingTop);
  }

  const setupDynamicElementSizing = () : void => {
    const actualScrollBarVertical: HTMLElement = resizeBarVerticalDiv.childNodes[0] as HTMLElement;
    const actualScrollBarHorizontal: HTMLElement = resizeBarHorizontalDiv.childNodes[0] as HTMLElement;

    actualScrollBarVertical.style.width = getComputedStyle(resizeBarVerticalDiv).width;
    actualScrollBarHorizontal.style.height = getComputedStyle(resizeBarHorizontalDiv).height;

    actualScrollBarVertical.style.left = "50%";
    actualScrollBarHorizontal.style.left = "50%";
    actualScrollBarVertical.style.transform = `translate(-50%)`;
    actualScrollBarHorizontal.style.transform = `translate(-50%)`;
  }


  const handleDownHorizontal = (e: MouseEvent) => {
    e.preventDefault();
    isDraggingHorizontal = true;
    document.addEventListener('mousemove', handleMouseDraggedHorizontal);
    document.addEventListener('mouseup', handleReleaseHorizontal);
    document.body.style.cursor = "col-resize";
    document.body.style.userSelect = "none"; 
  }

  const handleDownVertical = (e: MouseEvent) => {
    e.preventDefault();
    isDraggingVertical = true;
    document.addEventListener('mousemove', handleMouseDraggedVertical);
    document.addEventListener('mouseup', handleReleaseVertical);
    document.body.style.cursor = "row-resize";
    document.body.style.userSelect = "none"; 
  }


  const handleMouseDraggedHorizontal = (e: MouseEvent) => {
    if (!isDraggingHorizontal) return;
    const dx = originalWidthLeft + contentPaneClientStartX - e.clientX;
    let newDataDivWidth: number = originalWidthLeft - dx;
    let newCodeDivWidth: number = originalWidthRight + dx;
    // TODO magic number, make this relative or a const, could be percentage of DOMRect but considering how often this fires that seems unwise
    if (newDataDivWidth < 50){
      newCodeDivWidth += newDataDivWidth;
      newDataDivWidth = 0;
      handleReleaseHorizontal();
      hideVerticalBarWrapper();
      isDataDivSnappedToLeft = true;
      resizeVerticalButton.style.visibility = "visible";
    }
    dataDiv.style.width = `${newDataDivWidth}px`;
    codeDiv.style.width = `${newCodeDivWidth}px`;   
  }

  const handleMouseDraggedVertical = (e: MouseEvent) => {
    if (!isDraggingVertical) return;
    const dy = originalHeightTop + contentPaneClientStartY - e.clientY;
    monacoDiv.style.height = `${originalHeightTop - dy}px`;
    terminalDiv.style.height = `${originalHeightBottom + dy}px`;
  }

  const handleReleaseHorizontal = () => {
    isDraggingHorizontal = false;

    document.removeEventListener('mousemove', handleMouseDraggedHorizontal);
    document.removeEventListener('mouseup', handleReleaseHorizontal);
    document.body.style.cursor = "auto";
    document.body.style.userSelect = "auto";

    wasClicked = true;
  }

  const handleReleaseVertical = () => {
    isDraggingVertical = false;

    document.removeEventListener('mousemove', handleMouseDraggedVertical);
    document.removeEventListener('mouseup', handleReleaseVertical);
    document.body.style.cursor = "auto";
    document.body.style.userSelect = "auto";

    wasClicked = true;

  }

  const toggleVerticalWindowResizeBarResized = () => {
    if (isDraggingHorizontal) return;
    const resize_bar_width = parseComputedDimensions(getComputedStyle(verticalResizeBar).width);
    if (!isVerticalResized){
      verticalResizeBar.style.width = `${resize_bar_width * 3}px`
      isVerticalResized = true;
      verticalResizeBarAccent.style.visibility = "visible";

      if(theme === "dark"){
        verticalResizeBar.style.background = "rgba(255,255,255,0.35)";
      }else{
        verticalResizeBar.style.background = "#FF0000";
      }
    }else {
      isVerticalResized = false;
      verticalResizeBar.style.background = "var(--color-bg)";
      verticalResizeBar.style.width = `${resize_bar_width / 3}px`
      verticalResizeBarAccent.style.visibility = "hidden";

    }
    verticalResizeBar.style.left = "50%";
    verticalResizeBar.style.transform = `translate(-50%)`;  
  }

  const toggleHorizontalWindowResizeBarResized = () => {
    if (isDraggingVertical) return;
    const resize_bar_height = parseOptionalDimensions(horizontalResizeBarComputedStyle?.height);
    if (!isHorizontalResized){
      isHorizontalResized = true;
      horizontalResizeBar.style.height = `${resize_bar_height * 3}px`
      horizontalResizeBarAccent.style.visibility = "visible";
      if(theme === "dark"){
        horizontalResizeBar.style.background = "rgba(255,255,255,0.35)";
      }else{
        horizontalResizeBar.style.background = "#FF0000";
      }
    }else{
      isHorizontalResized = false;
      horizontalResizeBar.style.height = `${resize_bar_height / 3}px`;
      horizontalResizeBar.style.background = "var(--color-bg)";
      horizontalResizeBarAccent.style.visibility = "hidden";
    }
    horizontalResizeBar.style.top = "50%";
    horizontalResizeBar.style.transform = `translate(-50%)`; 
  }

  const expandVerticalBarWrapper = ()=>{
    if (!isDataDivSnappedToLeft){
      if (isHorizontalResized && !isDraggingHorizontal){
        handleReleaseVertical();
        toggleHorizontalWindowResizeBarResized();      
      }
      toggleVerticalWindowResizeBarResized();
    }
  }

  const hideVerticalBarWrapper = () => {
    if(!isDataDivSnappedToLeft){
      if(!isDraggingHorizontal && !isDraggingVertical && wasClicked){
        wasClicked = false;
        if (isVerticalResized){
          toggleVerticalWindowResizeBarResized();      
        }
      }else{
          toggleVerticalWindowResizeBarResized();
      }
    }
  }

  const expandHorizontalBarWrapper = ()=>{
    if (!isDraggingHorizontal){
      toggleHorizontalWindowResizeBarResized();
    }
  }

  const hideHorizontalBarWrapper = ()=>{
    if(!isDraggingVertical && wasClicked){
      wasClicked = false;
      if(isHorizontalResized){
        toggleHorizontalWindowResizeBarResized();
      }
    }else{
      toggleHorizontalWindowResizeBarResized();
    }
  }
  const returnInfoDiv = (): void => {
    const rect: DOMRect = document.body.getBoundingClientRect();
    dataDiv.style.width = `${rect.width * 0.2}px`;
    codeDiv.style.width = `${rect.width * 0.8}px`;
    resizeVerticalButton.style.visibility = "hidden";
    isDataDivSnappedToLeft = false;

  }

</script>

<!-- svelte-ignore a11y_click_events_have_key_events -->
<!-- svelte-ignore a11y_no_static_element_interactions -->
<!-- svelte-ignore a11y_no_static_element_interactions -->
<main bind:this={mainDiv} class="flex h-[84vh] w-full my-5 bg-[var(--color-bg)]">
  <!-- svelte-ignore a11y_click_events_have_key_events -->
  <div bind:this={resizeVerticalButton} class="h-[20%] w-4 rounded-r-md bg-[var(--color-tile)] border-2 border-[var(--color-primary)] border-l-0 fixed left-0 top-[40%] invisible z-999 flex justify-center items-center hover:cursor-pointer" onclick={returnInfoDiv}>
    <div class="transform rotate-90 origin-center">huh</div>  
</div>

  <HelperDuck/>

  <ExerciseInformation {data} bind:dataDiv />
  <!-- {@render ExerciseInformation()} -->

  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div 
    bind:this={resizeBarVerticalDiv}
    class="w-1 h-full relative overflow-visible" 
    class:hover:cursor-col-resize={!isDraggingHorizontal}
    onmouseenter={expandVerticalBarWrapper}
    onmouseleave={hideVerticalBarWrapper}
    onmousedown={handleDownHorizontal}
    onmouseup={handleReleaseHorizontal}
  >
  <div 
    bind:this={verticalResizeBar}
    class="h-full absolute flex flex-col justify-center items-center rounded-full"
  >

    <div bind:this={verticalResizeBarAccent} class="w-1 h-25 bg-[var(--color-accent-1)] rounded-full none invisible"></div>
  </div>
</div>
  {@render CodeEditor()}
</main>


{#snippet CodeEditor()}
  <div bind:this={codeDiv} class="w-full h-full flex flex-col px-1">
      <div bind:this={monacoDiv} class="w-full h-[85%] rounded-t-md overflow-hidden" bind:this={editorContainer}></div>
      <!-- svelte-ignore a11y_no_static_element_interactions -->
        <div 
          id="resize-bar-holder-horizontal" 
          bind:this={resizeBarHorizontalDiv}
          class="h-1 w-full relative overflow-visible"
          class:hover:cursor-row-resize={!isDraggingVertical}
          onmouseenter={!isDraggingVertical ? expandHorizontalBarWrapper : undefined}
          onmouseleave={!isDraggingHorizontal ? hideHorizontalBarWrapper : undefined}
          onmousedown={handleDownVertical}
          onmouseup={handleReleaseVertical}
        >
          <div bind:this={horizontalResizeBar} class="w-full absolute flex justify-center items-center rounded-full">
            <div bind:this={horizontalResizeBarAccent} class="w-25 h-1 bg-[var(--color-accent-1)] rounded-full none invisible"></div>
          </div>
        </div>
      <div bind:this={terminalDiv} class="w-full h-[15%] bg-[var(--color-tile)] px-3 py-1 rounded-b-md ">
        <span class="font-mono">&#123;username&#125;@&#123;exercise_name&#125;:/home/&#123;username&#125;/terminal$ </span>
      </div>
  </div>
{/snippet}